### ISSUE TITLE
Viewer crashes when interacting with it

### ISSUE THREAD

**Issue by wjcramer** [dendrograms/astrodendro#196]
Hi,

I've had success running astrodendro, but run into issues when trying to display the results with:

`v = d.viewer()`
`v.show()`

I'm running with the downgraded Matplotlib and Numpy libraries as previous issues noted were necessary, but still get this error message when trying to click on anything within the viewer window:

`Traceback (most recent call last):
  File "/Users/wcramer2/miniconda3/envs/astrodendro/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/Users/wcramer2/miniconda3/envs/astrodendro/lib/python3.8/site-packages/astrodendro/viewer.py", line 245, in select_from_map
    self.hub.select(input_key, structure)
  File "/Users/wcramer2/miniconda3/envs/astrodendro/lib/python3.8/site-packages/astrodendro/viewer.py", line 57, in select
    cb(id)
  File "/Users/wcramer2/miniconda3/envs/astrodendro/lib/python3.8/site-packages/astrodendro/viewer.py", line 202, in _on_selection_change
    self._update_lines(selection_id)
  File "/Users/wcramer2/miniconda3/envs/astrodendro/lib/python3.8/site-packages/astrodendro/viewer.py", line 299, in _update_lines
    self.remove_all_contours()
  File "/Users/wcramer2/miniconda3/envs/astrodendro/lib/python3.8/site-packages/astrodendro/viewer.py", line 329, in remove_all_contours
    for key in self.selected_contour.keys():
RuntimeError: dictionary changed size during iteration`

I saw a previous issue reported about dictionaries here: https://github.com/dendrograms/astrodendro/pull/181 but it looked like that had already been fixed and merged into the current version of astrodendro and I wondered if this was the same issue, or there were any other solutions.

thanks!

**Comment by astrofrog** [comment]
This should be fixed in astrodendro v0.3.1, released today
